### ISSUE TITLE
Simplify EES tests

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#51]
The EES tests can currently take [up to 20 mins to run on Travis](https://travis-ci.org/agentsoz/bdi-abm-integration/builds/405141722) and around 14 mins on a standard laptop. 

The tests should be consolidated as there is significant overlap in tests now. Overall it would be good to remove some tests, and scale down some others to 10% and such so that overall the tests run in less than 5 mins.

**Comment by dhixsingh** [comment]
After discussion with @osbornejr, have disabled a few tests that are not adding much value to the testing. Since commit 9684279 `mvn test` on my machine takes just under 4 minutes. The [last full run on travis took just under 10 mins](https://travis-ci.org/agentsoz/bdi-abm-integration/builds/411141021).

@osbornejr note that your commit a3f176d had broken travis; I've fixed this in 5d5e890.

**Comment by dhixsingh** [comment]
Since 9283989 `mvn clean install` takes *less than 3 minutes*  on my machine and [under 7 minutes on Travis](https://github.com/agentsoz/bdi-abm-integration/commit/928398962d9d7addc882d1f2fe1d128adb63fdfe).

**Comment by dhixsingh** [comment]
@osbornejr `testOtways300Tourist` is the only remaining test now that has >50 agents. Would you mind creating a `testOtways300TouristReduced` test that has ~30-50 agents instead?

See how I do this for [MainMaldon600Test](https://github.com/agentsoz/bdi-abm-integration/blob/928398962d9d7addc882d1f2fe1d128adb63fdfe/examples/bushfire/src/test/java/io/github/agentsoz/ees/MainMaldon600Test.java#L29). I left he original test unchanged (ignored), and just enabled the reduced version.

After that, this issue can be closed.

**Comment by osbornejr** [comment]
Done as of 8e8254f0b3a338d8b8fa761485d8b266ce60d6a1.

**Comment by dhixsingh** [comment]
@osbornejr seems like you missed pushing the actual test `testOtways300TouristReduced` for this?

**Comment by osbornejr** [comment]
Apologies. Should be good as of 59f5d4c9778f320d8bd46956c10aa9cde9cd56c0.
